idf_component_register(SRCS "tasks/tasks/leds/task_led.c" 
                            "tasks/tasks/sensors/reed/task_reed.c"
                            "system/system_state.c"
                            "tasks/tasks/alarm/task_alarm.c"
                            "tasks/tasks/sensors/button/task_button.c"
                            "system/alarm_queue/alarm_queue.c"
                            "wifi/wifi.c"
                            "communication/http_server/http_server.c"
                            "communication/http_client/http_client.c"
                            "events/event.c"
                            "main.c"

                    INCLUDE_DIRS "."
                                "tasks/tasks/leds"
                                "tasks/tasks/sensors/reed"
                                "tasks/tasks/sensors/button"
                                "tasks/tasks/alarm"
                                "system/alarm_queue"
                                "wifi"
                                "system"
                                "communication/http_server"
                                "communication/http_client"
                                "events")
